### PR TITLE
Adding Battlesnake

### PR DESCRIPTION
**Pull request by andrewdmaclean**
Hope this is the best way to contribute! Happy to make any revisions needed for the PR to be merged 😄

### CODE REVIEW

**Comment by andrewdmaclean** [comment]
Hey @readyready15728 just checking in to see if there was anything needed for this PR?

**Comment by andrewdmaclean** [comment]
Hey @readyready15728 👋 Just checking in again - anything needed to merge this PR?

**Comment by andrewdmaclean** [comment]
Hey @readyready15728 👋 Sorry for the poke again, but just checking in if there is anything that I can do to move this PR forward?

**Comment by andrewdmaclean** [comment]
@readyready15728 any idea if this PR will ever be merged?

**Comment by readyready15728** [comment]
Thanks for your persistence. I am buried in unread emails and am trying to catch up. Your PR has been merged.

**Pull request merged**
