### PR TITLE
Adding Factorio

### PR DESCRIPTION
**Pull request by madbarron**

### CODE REVIEW

**Comment by readyready15728** [comment]
Will consider once I find out how essential programming is in Factorio.

**Comment by readyready15728** [comment]
With all due respect I'm going to close this one. Factorio looks like a fantastic game but I need programming to be a _key_ element in the gameplay, whereas it is optional in Factorio.

**Comment by madbarron** [comment]
Totally up to you of course! For me, when the game is all about arranging conveyer belts, arms, and assemblers, playing it feels like programming. Compare to Automachef, which is on the list.

**Comment by microspace** [comment]
Maybe we should add category such as "Programmable games"?

**Pull request closed without merging**
